ANDROID: fuse: fix struct path zero initialization
It seems gcc is too strict and doesn't recognize {0} as a valid implicit
zero initialization for structs with randomize layouts. This triggers
the following build issue:

  ./include/linux/fsnotify.h:105:51: error: positional initialization of
      field in ‘struct’ declared with ‘designated_init’ attribute
      [-Werror=designated-init]
    105 |                         struct path lower_path = {0};

Instead of calling for the first positional member to be explicitly zero
use {} as a zero initializer for the whole struct and make gcc happy.

Fixes: 44a94ece4726 ("ANDROID: fuse: Support errors from fuse daemon in canonical path")
Change-Id: I6b474f44657b5add16a8df5fdb3a4a0919377c2c
Signed-off-by: Carlos Llamas <cmllamas@google.com>
(cherry picked from commit f3a30a028ef9a46f55b3e087854833426619e02c)